---
- name: Example
  hosts: 127.0.0.1
  connection: local
  vars:
    spam_login: "{{ lookup('keepass', 'spam', 'username')}}"
    spam_password: "{{ lookup('keepass', 'spam', 'password')}}"
    ham_login: "{{ lookup('keepass', 'examples/ham', 'username')}}"
    ham_password: "{{ lookup('keepass', 'examples/ham', 'password')}}"
    pork_custom_property: "{{ lookup('keepass', 'examples/pork', 'pork_custom_property', true)}}"

  tasks:
    - debug:
        msg: "fetch group: /    username: {{ spam_login }}    password: {{ spam_password }}"

    - debug:
        msg: "fetch group: /examples/ham     username: {{ ham_login }}   password: {{ ham_password }}"

    - debug:
        msg: "fetch group: /examples/pork     pork_custom: {{ pork_custom_property }}"